### ISSUE TITLE
Datasheet

### ISSUE THREAD

**Issue by mohdumar644** [Bill2462/MPU9255-Arduino-Library#20]
Which datasheet (pdf) did you refer to?
Yours is the only library having WHO_AMI_I register at 0x77 and the only library which is working with my CJ sensor.

**Comment by Bill2462** [comment]
[MPU-9255-Register-Map.pdf](https://github.com/Bill2462/MPU9255-Arduino-Library/files/2604493/MPU-9255-Register-Map.pdf)
[MPU-9255-Datasheet.pdf](https://github.com/Bill2462/MPU9255-Arduino-Library/files/2604500/MPU-9255-Datasheet.pdf)

**Comment by Bill2462** [comment]
I just noticed an error in addres definitions. 
WHO_AM_I register should be on 0x75. Not on 0x77.

**Comment by Bill2462** [comment]
Fixed in: a08aba3
